In [5]:
# Good evening sir,my name is Siddhartha Tiwari CCE 'B' 23FE10CCE00085
# this is my 2nd foundation of data science assignment

# I have provided comment for each step to make it easy for other to understand 



#1. Matrix Operations
#This code performs addition, subtraction, multiplication, 
#element-wise multiplication, determinant, and inverse of a matrix
#using NumPy and SciPy.


# Import necessary libraries
import numpy as np
from scipy.linalg import det, inv  # For determinant and inverse

# Define two matrices
A = np.array([[1, 2], [3, 4]])  # Matrix A
B = np.array([[5, 6], [7, 8]])  # Matrix B

# Display the matrices
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# 1. Addition of matrices
addition = A + B
print("\n1. Addition (A + B):")
print(addition)

# 2. Subtraction of matrices
subtraction = A - B
print("\n2. Subtraction (A - B):")
print(subtraction)

# 3. Matrix multiplication (dot product)
multiplication = np.dot(A, B)
print("\n3. Multiplication (A * B):")
print(multiplication)

# 4. Element-wise multiplication
element_wise_multiplication = A * B
print("\n4. Element-wise Multiplication (A .* B):")
print(element_wise_multiplication)

# 5. Determinant of a matrix
determinant_A = det(A)
print("\n5. Determinant of Matrix A:")
print(determinant_A)

# 6. Inverse of a matrix
if determinant_A != 0:  # Check if the determinant is non-zero
    inverse_A = inv(A)
    print("\n6. Inverse of Matrix A:")
    print(inverse_A)
else:
    print("\n6. Matrix A is singular and does not have an inverse.")








#2. Eigenvalues and Eigenvectors
#This code calculates the eigenvalues and eigenvectors of 
#a matrix and checks the orthogonality of the eigenvectors.


# Define a square matrix
C = np.array([[4, -2], [1, 1]])  # Example matrix

# Display the matrix
print("\nMatrix C:")
print(C)

# 1. Calculate Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)

# Display the eigenvalues
print("\n1. Eigenvalues of Matrix C:")
print(eigenvalues)

# Display the eigenvectors
print("\n2. Eigenvectors of Matrix C:")
print(eigenvectors)

# 2. Check Orthogonality of Eigenvectors
print("\n3. Checking Orthogonality of Eigenvectors:")

# Loop through all pairs of eigenvectors
for i in range(len(eigenvectors)):
    for j in range(i + 1, len(eigenvectors)):
        # Compute the dot product of eigenvector i and eigenvector j
        dot_product = np.dot(eigenvectors[:, i], eigenvectors[:, j])
        print(f"Dot product of Eigenvector {i + 1} and {j + 1}: {dot_product}")

        # Check if the dot product is close to zero
        if np.isclose(dot_product, 0):
            print(f"Eigenvector {i + 1} and Eigenvector {j + 1} are orthogonal.")
        else:
            print(f"Eigenvector {i + 1} and Eigenvector {j + 1} are NOT orthogonal.")










#3. Span and Basis of a Vector Space
#This code calculates the span and
#basis of a vector space using NumPy.


# Define a set of vectors
vectors = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example vectors

# Display the vectors
print("\nGiven Vectors:")
print(vectors)

# 1. Calculate the Basis of the Vector Space
# Use NumPy's `linalg.matrix_rank` to find the rank of the matrix formed by the vectors
rank = np.linalg.matrix_rank(vectors)

# Use QR decomposition to extract the independent vectors (basis)
Q, R = np.linalg.qr(vectors.T)  # Transpose the matrix to work with columns
basis = Q[:, :rank].T  # Take the first 'rank' columns of Q and transpose back

# Display the basis
print("\n1. Basis of the Vector Space:")
print(basis)

# 2. Calculate the Span of the Vector Space
# The span of the vector space is the set of all linear combinations of the basis vectors
# We will demonstrate this by generating a few random linear combinations

print("\n2. Span of the Vector Space (Example Linear Combinations):")
coefficients = np.random.rand(5, rank)  # Generate random coefficients for 5 combinations
span_examples = np.dot(coefficients, basis)  # Compute linear combinations

# Display the examples of vectors in the span
for i, span_vector in enumerate(span_examples, start=1):
    print(f"Example {i}: {span_vector}")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

1. Addition (A + B):
[[ 6  8]
 [10 12]]

2. Subtraction (A - B):
[[-4 -4]
 [-4 -4]]

3. Multiplication (A * B):
[[19 22]
 [43 50]]

4. Element-wise Multiplication (A .* B):
[[ 5 12]
 [21 32]]

5. Determinant of Matrix A:
-2.0

6. Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Matrix C:
[[ 4 -2]
 [ 1  1]]

1. Eigenvalues of Matrix C:
[3. 2.]

2. Eigenvectors of Matrix C:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

3. Checking Orthogonality of Eigenvectors:
Dot product of Eigenvector 1 and 2: 0.9486832980505137
Eigenvector 1 and Eigenvector 2 are NOT orthogonal.

Given Vectors:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. Basis of the Vector Space:
[[-0.26726124 -0.53452248 -0.80178373]
 [ 0.87287156  0.21821789 -0.43643578]]

2. Span of the Vector Space (Example Linear Combinations):
Example 1: [ 0.69070209  0.05901105 -0.57267998]
Example 2: [ 0.03577499 -0.05851044 -0.15279588]
Example 3: [ 0.17623781 -0.00484203 -0.18592187]
Example 4: